### ISSUE TITLE
Searching for IDs in the Trace Window

### ISSUE THREAD

**Issue by kistenklaus** [mu-zero-HYPERLOOP/control-panel#26]
It would be quite cool, if we could for example search for 0x100 and only get the messages of this id!
This would have to be in addition to searching by name.

I would really appreciate if both use the same search bar so for example if we search for 
secu_temperature, we would get all messages that contain secu_temperature in their name 
and if we search for 412, we get all messages where the id as a decimal contains 412, and 0x100, we get all that contain 0x100 
in their hexadecimal id!

**Comment by Nico4899** [comment]
Almost done :)
You search for decimal integers like "102" and get the hex value "0x66".
Better if you are able to search for hex ids as well

**Comment by Nico4899** [comment]
With Fuse.js you can decide whether you want to list only matching frame names or ids or list the closest matching results, based on the distance.
