### ISSUE TITLE
Set ObjectEntry request protocol

### ISSUE THREAD

**Issue by kistenklaus** [mu-zero-HYPERLOOP/control-panel#28]
We wan't to be able to set a object entry from the control panel, therefor the set protocol has to be implemented 
preferrable in the ObjectEntryObject.

**Comment by kistenklaus** [comment]
command is done in commands/object_entry_information.rs

**Comment by kistenklaus** [comment]
Now only the timeout and handling of responses has to be implemented! Pretty Close

**Comment by arrowtip** [comment]
sending of set requests is now implemented and merged
