### ISSUE TITLE
Set ObjectEntry command

### ISSUE THREAD

**Issue by kistenklaus** [mu-zero-HYPERLOOP/control-panel#29]
We need a command to set the value of a ObjectEntry from the view. 
This should not directy set the object entry, but instead invoke the set protocol.

For now this means calling a function of a ObjectEntryObject, it doesn't exist yet but for example set(&self, value : TypeValue)

The compilicated part here is that we have to implement Deserialize for TypeValue or a seperate type, which i have no idea how to do?

**Comment by NiklasHeneka** [comment]
Where should we be able to set the ObjectEntry command? In the trace panel, the ObjectEntry table from the side bar or somewhere else?

**Comment by kistenklaus** [comment]
right now implemented it is meant to be with the edit button on the object entry panel

**Comment by kistenklaus** [comment]
from the backend a lot of stuff actually still has to happen here. Currently we are only able to Serialize values from rust. But for the set command we need to Deserilize the JSON objects from javascript into rust structs. This is probably the holdup right now from the backend
