### ISSUE TITLE
Optimze table efficiency by using "Virtuoso"

### ISSUE THREAD

**Issue by Nico4899** [mu-zero-HYPERLOOP/control-panel#33]

**Comment by Nico4899** [comment]
https://virtuoso.dev/

**Comment by NiklasHeneka** [comment]
Only for the trace panel or should we use it for the tables in the overview like the heat map aswell?

**Comment by Nico4899** [comment]
Would make sense for trace panel, since we are dealing with hundreds if not
thousand of messages. So anywhere where we work with a lot of data in a
short period of time it would make sense to use virtuoso for table
structures

Niklas Heneka ***@***.***> schrieb am Do., 30. Nov. 2023,
17:40:
