### ISSUE TITLE
Make Liskov happy

### ISSUE THREAD

**Issue by kistenklaus** [mu-zero-HYPERLOOP/control-panel#35]
Currently the Message Handlers have to return a Frame type, which is a super class for all Frames, but for example a 
TypeFrameParser, should just return a TypeFrame! This doesn't break Liskovsch Sub rule, but requires some changes.

MessageParser subclasses should return the most specific type and invoking it on a MessageParser (superclass) should return a Frame (abstract class). 

 This is actually pretty cool that rust allows for that =^)

**Comment by arrowtip** [comment]
Irrelevant when removing differentiation between Type- and SignalFrame altogether
