### ISSUE TITLE
Notifaction System for the view

### ISSUE THREAD

**Issue by kistenklaus** [mu-zero-HYPERLOOP/control-panel#42]
We should have a proper notification system, where the view gets notified if anything happens in the backend.
This will eventually be a event that the view can listen to to get notified about any errors in the backend 
notifaction will be classified in:
Info: 
Warning:
Error:

all contain a message describing the error. 
the type of notification should be displayed by color.

Optionally if a higher priority notification is send the lower priority notifications 
should not be shown. And for errors it should be garanteed that they are shown in less than 100ms in the view!

Here are some resources i found on this already:
- MaterialUI offers something for this https://mui.com/material-ui/react-snackbar/

- Notistack is a library that does the same, but with a provider pattern, this might be more usable if we also want to send notifications from the frontend and not just from the backend. https://github.com/iamhosseindhv/notistack#online-demo

**Comment by kistenklaus** [comment]
@NiklasHeneka interessted?

**Comment by NiklasHeneka** [comment]
Display of Notifications is finished. The priority is still in progress.
