### ISSUE TITLE
Filter delta_time in the Trace window

### ISSUE THREAD

**Issue by kistenklaus** [mu-zero-HYPERLOOP/control-panel#43]
The delta_time is super noisy right now, but we can expect the frames especially from streams to have consistant delta_times.

Because we batch messages together anyway one idea should be to calculate a moving average across the delta_time and send the filtered delta_time to the view!

Another alternative in my opinion, slightly better, would be to calculate an average across the delta_times that have been accumulated for a frame since the last notify to the view. This would however require a more complex data structure of the trace object

**Comment by kistenklaus** [comment]
stupid if delta_time should be accurate

**Comment by kistenklaus** [comment]
Maybe a wontfix. Please discuss
@NiklasHeneka 
@arrowtip 
@Nico4899

**Comment by NiklasHeneka** [comment]
Close it as won't fix and wait. If we need it we can still reopen it.

**Comment by kistenklaus** [comment]
yep agree with that @NiklasHeneka
