### ISSUE TITLE
Frontend file structure

### ISSUE THREAD

**Issue by NiklasHeneka** [mu-zero-HYPERLOOP/control-panel#45]
Should we change the file structure of the frontend? Having so many files in components is just confusing.
Maybe we can structure the packages according to their page. Like this:

Overview
- Buttons...

Trace
- TraceGrid
- Types

Node Panels
- Specific page

Or idk maybe something else just think it is not very nice rigth now.

**Comment by kistenklaus** [comment]
feel free to do the changes the way you want to i think you now the frontend the best
