### ISSUE TITLE
Correct handling of buses in the control-panel

### ISSUE THREAD

**Issue by kistenklaus** [mu-zero-HYPERLOOP/control-panel#50]
The config now defines buses, which should be used by the control-panel to create the correct number of bus adapters and to create seperate lookup tables for handlers dependent on the bus. 

This is absolutely required because to message might have the same id now! (if assigned to different can buses)

**Comment by kistenklaus** [comment]
whoopsi dupsi RxCom is done with #79

**Comment by kistenklaus** [comment]
missing TxCom! @arrowtip close on merge please

**Comment by arrowtip** [comment]
done and merged
