### ISSUE TITLE
Deserialize TypeValues

### ISSUE THREAD

**Issue by kistenklaus** [mu-zero-HYPERLOOP/control-panel#55]
Currenty we are only able to serialize TypeValues in the backend, but for setting of ObjectEntries we have to be able to Deserialize TypeValues from a javascript Object. 

It should be noted here that 
x = Deserialize(Serialize(x)) 
doesn't actually have to be true for it to work probably 
but i would really appreciate if it did. But it it leads to problems it is actually not required!

**Comment by arrowtip** [comment]
Could not implement Deserialize since type information from config is not available in deserialize function.
Passing the value as a JSON string to the backend instead and implement a string parser.

**Comment by arrowtip** [comment]
feature implemented on feature/set-requests (f86a307c1d81367a93961a2a297e4e0088c42470) but not yet merged
