### ISSUE TITLE
Github actions

### ISSUE THREAD

**Issue by NiklasHeneka** [mu-zero-HYPERLOOP/control-panel#6]
Actions for running tests, building and code quality.

**Comment by kistenklaus** [comment]
i think the action should run ```npm run tauri dev``` instread of ```npm run tauri build``` because build fails on normal code warnings like unused import, at least for now where we commit a lot to main

**Comment by NiklasHeneka** [comment]
Added to run tauri actions only on main branch in [26a558c](https://github.com/mu-zero-HYPERLOOP/control-panel/commit/26a558cbeab8d6c8a6ada002df981a322a68d142).
If you see find a way to change build to dev in the actions you can change this as well.
