### ISSUE TITLE
Bad performance on startup.

### ISSUE THREAD

**Issue by NiklasHeneka** [mu-zero-HYPERLOOP/control-panel#61]
Starting the app currently takes several minutes. It seems it's trying to connect to http://100.123.16.144:8097/ and receives a timeout after some time which slows down the app.

**Comment by NiklasHeneka** [comment]
@kistenklaus

**Comment by kistenklaus** [comment]
will take a look at it. Any idea since when this is the case?

**Comment by NiklasHeneka** [comment]
It's interesting because at home the timeout happens very fast so the startup is only slowed down a little. However at KIT this takes much longer. The issue comes with [Pretty pretty graphs](https://github.com/mu-zero-HYPERLOOP/control-panel/commit/8bd7088e2510489d5e1347295d079721e6d64a96#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051) comit in the index.html file. This might also be the reason for a slow start in general.

**Comment by kistenklaus** [comment]
http://100.123.16.144:8097/ is the react-devtools debug server super weird bug i removed it because it is only required for performance debugging.

Also i don't have any problems on my PC and it only happend for me on my laptop, where i also have installed the react-devtools. Anyway can you check if 7380974 fixes it?

**Comment by kistenklaus** [comment]
you could also check if 
```
<script src="http://localhost:8097"></script>
```
works without major performance impact. Just out of interst

**Comment by kistenklaus** [comment]
https://github.com/facebook/react/tree/main/packages/react-devtools#usage-with-react-dom

if your interessted in what react-devtools is. It is very useful for debugging frame times and finding the slowest components

**Comment by NiklasHeneka** [comment]
Yes [7380974](https://github.com/mu-zero-HYPERLOOP/control-panel/commit/7380974a84fe7edf3e1d2e2397e26af93d578ed4) fixes it. With 
`<script src="http://localhost:8097"></script>`
I still get a connection error in the JS console but the startup is still much faster.
