### ISSUE TITLE
Error on startup.

### ISSUE THREAD

**Issue by NiklasHeneka** [mu-zero-HYPERLOOP/control-panel#70]
With commit [d742da8](https://github.com/mu-zero-HYPERLOOP/control-panel/commit/d742da827d7de435fd121b3802a715392a7051a3) I can no longer start the app @kistenklaus.

This is the error from the console:

error[E0658]: use of unstable library feature 'int_roundings'
  --> /Users/niklas/.cargo/git/checkouts/can-config-rs-617c2daf7c8870b1/9e21d33/src/builder/message_resolution/set_minimization/priority_bucket.rs:20:30
   |
20 |         self.message_count().div_ceil(bucket_size)
   |                              ^^^^^^^^
   |
   = note: see issue #88581 <https://github.com/rust-lang/rust/issues/88581> for more information

error[E0658]: use of unstable library feature 'int_roundings'
  --> /Users/niklas/.cargo/git/checkouts/can-config-rs-617c2daf7c8870b1/9e21d33/src/builder/message_resolution/set_minimization/priority_bucket.rs:28:34
   |
28 |                 Some(bucket_size.div_ceil(self.message_count() / bucket_size - 1))
   |                                  ^^^^^^^^
   |
   = note: see issue #88581 <https://github.com/rust-lang/rust/issues/88581> for more information

error[E0658]: use of unstable library feature 'int_roundings'
  --> /Users/niklas/.cargo/git/checkouts/can-config-rs-617c2daf7c8870b1/9e21d33/src/builder/message_resolution/set_minimization/priority_bucket.rs:30:27
   |
30 |                 Some(rest.div_ceil(self.message_count() / bucket_size))
   |                           ^^^^^^^^
   |
   = note: see issue #88581 <https://github.com/rust-lang/rust/issues/88581> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `can-config-rs` (lib) due to 3 previous errors

**Comment by kistenklaus** [comment]
cant reproduce can you give me the cargo version @NiklasHeneka

**Comment by NiklasHeneka** [comment]
Updating rustup solved the issue.

**Comment by kistenklaus** [comment]
to fix run 
```
rustup update
```
and check that the version is above 1.75.
